spring.application.name=backend-preu

spring.datasource.url=jdbc:h2:mem:backendpreu
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true

application.security.jwt.secret-key=5367566B5970337336763979244226452948404D6351665468576D5A71347437

logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr([%X{requestId}]){cyan} : %m%n

google.recaptcha.secret=TU_CLAVE_SECRETA_PEGA_AQUI_LA_LARGA
google.recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify