package com.backend.backendpreu.auth.dto;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for user login requests.
 * Contains the user's email, password, and reCAPTCHA token for authentication.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class LoginRequestDTO {
    /**
     * The email address of the user attempting to log in.
     */
    private String email;
    /**
     * The password of the user attempting to log in.
     */
    private String password;
    /**
     * The reCAPTCHA token generated by the client to verify human interaction.
     */
    private String captchaToken;
}
